# Práctica 2 Ingeniería Linguística

In [121]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_files
import numpy as np
import glob
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
def open_glossary():
    file_deportes = open("./Glosarios/Glosario_deportes/glosario_deportes.txt",encoding='utf-8')
    glosario_deportes = file_deportes.read().split("\n")
    
    file_politica = open("./Glosarios/Glosario_politica/glosario_politica.txt",encoding='utf-8')
    glosario_politica = file_politica.read().split("\n")
    
    file_salud = open("./Glosarios/Glosario_salud/glosario_salud.txt",encoding='utf-8')
    glosario_salud = file_salud.read().split("\n")
    
    glosarios = [glosario_deportes,glosario_politica,glosario_salud]
    
    return glosarios

In [3]:
glosario = open_glossary()
glosario_deportes = glosario[0]
glosario_politica = glosario[1]
glosario_salud = glosario[2]

In [30]:
def load_documents(filenames):
    documents = []
    for i in filenames:
        file_document = open(i,encoding='utf-8')
        documents.append(file_document.read().split())
    
    return documents

In [33]:
filenames_deportes = glob.glob('./Documentos/Deportes/*')
filenames_politica = glob.glob('./Documentos/Politica/*')
filenames_salud = glob.glob('./Documentos/Salud/*')


documentos_deportes = load_documents(filenames_deportes)
documentos_politica = load_documents(filenames_politica)
documentos_salud = load_documents(filenames_salud)

In [53]:
##########################################

In [192]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
#nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
articles = load_files(r"./Documentos/",encoding='utf-8')
X, y = articles.data, articles.target

In [138]:
print(y)
print(len(X))


[0 0 1 1 2 0 1 1 1 2 0 0 1 2 0 0 0 2 2 1 0 0 2 1 2 1 2 2 2 0 2 2 0 0 1 1 2
 1 1 0 0 0 1 1 0 2 2 0 1 0 1 0 1 0 1 0 1 2 1 2 0 1 2 0 2 0 0 1 2 2 2 0 2 2
 0 1 1 1 2 1 0 2 1 0 2 0 2 2 2 1 1]
91


In [102]:
documents = []
for d in range(0, len(X)):
    document = re.sub(r'\W', ' ', str(X[d]))
    document = document.lower()
    documents.append(document)

In [103]:
vectorizer_deportes = CountVectorizer(vocabulary = glosario[0],ngram_range=(1, 2))
vectorizer_politica = CountVectorizer(vocabulary = glosario[1],ngram_range=(1, 2))
vectorizer_salud = CountVectorizer(vocabulary = glosario[2],ngram_range=(1, 2))


vocabulario = {0: glosario[0],1: glosario[1],2:glosario[2]}


vectorizer_ = CountVectorizer(vocabulary = glosario,ngram_range=(1, 2))

print(vectorizer_)

CountVectorizer(ngram_range=(1, 2),
                vocabulary=[['ganar', 'derbi', 'Real Madrid', 'Madrid',
                             'Atlético de Madrid', 'Atleti', 'olímpicos',
                             'final', 'rival', 'partido', 'partidos',
                             'deportivo', 'penalti', 'liga', 'fútbol', 'equipo',
                             'equipos', 'aficionados', 'futbolistas', 'torneo',
                             'club', 'balón', 'gol'],
                            ['artículo', 'gobierno', 'ley', 'constitución',
                             'reforma', 'mayoría', 'debate', 'parte', 'rey',
                             'congreso', 'comisión', 'país', 'derecho',
                             'ministerio', 'públicos', 'comunidad', 'partido',
                             'laboral', 'política', 'electoral'],
                            ['asma', 'defectos', 'medicamentos', 'salud',
                             'azúcar', 'caso', 'estudio', 'riesgo',
                     

In [152]:
X_deportes = vectorizer_deportes.fit_transform(documents).toarray()
X_politica = vectorizer_politica.fit_transform(documents).toarray()
X_salud = vectorizer_salud.fit_transform(documents).toarray()

print((X_deportes[0]))
print((X_politica[0]))
print((X_salud[0]))

X = [X_deportes,X_politica,X_salud]

[0 0 0 0 0 0 0 1 0 0 1 0 2 0 0 2 0 0 0 0 0 5 5]
[0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [154]:
len(X[2])

91

In [143]:
vector_glosario = [1,1,1,1,1,1,1,1]

In [ ]:
from scipy import spatial

dataSetI = [3, 45, 7, 2]
dataSetII = [2, 54, 13, 15]
result = 1 - spatial.distance.cosine(dataSetI, dataSetII)

In [161]:
tfidfconverter = TfidfTransformer()
X_deportes = tfidfconverter.fit_transform(X_).toarray()
print(X_[0])

[0.         0.         0.         0.         0.         0.
 0.         0.0802526  0.         0.         0.09030799 0.
 0.31301098 0.         0.         0.18398048 0.         0.
 0.         0.         0.         0.6766357  0.62908142]


In [208]:
vocabulario = {0: glosario[0],1: glosario[1],2:glosario[2]}
type(vocabulario)

dict

In [207]:
X_train, X_test, y_train, y_test = train_test_split(documents, y, test_size=0.5, random_state=0)


vocabulario = {0: glosario[0],1: glosario[1],2:glosario[2]}

Tfidf_vect = TfidfVectorizer(vocabulary = vocabulario)
Tfidf_vect.fit(documents)

Train_X_Tfidf = Tfidf_vect.transform(X_train)
Test_X_Tfidf = Tfidf_vect.transform(X_test)

Modelo = SGDClassifier(loss='hinge',penalty='l2',alpha=1e-3, max_iter=20, random_state=42)
Modelo.fit(Train_X_Tfidf, y_train)
y_pred = Modelo.predict(Test_X_Tfidf)
print(accuracy_score(y_test, y_pred))
print(y_pred)

TypeError: unhashable type: 'list'

In [202]:
X_train, X_test, y_train, y_test = train_test_split(documents, y, test_size=0.5, random_state=0)

Tfidf_vect = TfidfVectorizer(vocabulary = glosario[1])
Tfidf_vect.fit(documents)

Train_X_Tfidf = Tfidf_vect.transform(X_train)
Test_X_Tfidf = Tfidf_vect.transform(X_test)

Modelo = SGDClassifier(loss='hinge',penalty='l2',alpha=1e-3, max_iter=20, random_state=42)
Modelo.fit(Train_X_Tfidf, y_train)
y_pred = Modelo.predict(Test_X_Tfidf)
print(accuracy_score(y_test, y_pred))
print(y_pred)

0.6086956521739131
[1 1 0 0 2 0 2 1 0 1 1 2 0 1 1 1 0 0 0 1 1 1 2 1 0 2 0 0 2 2 0 1 0 0 0 2 1
 0 2 0 0 2 2 0 2 1]


C:\Users\Fernando\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:570: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


In [203]:
X_train, X_test, y_train, y_test = train_test_split(documents, y, test_size=0.5, random_state=0)

Tfidf_vect = TfidfVectorizer(vocabulary = glosario[2])
Tfidf_vect.fit(documents)

Train_X_Tfidf = Tfidf_vect.transform(X_train)
Test_X_Tfidf = Tfidf_vect.transform(X_test)

Modelo = SGDClassifier(loss='hinge',penalty='l2',alpha=1e-3, max_iter=20, random_state=42)
Modelo.fit(Train_X_Tfidf, y_train)
y_pred = Modelo.predict(Test_X_Tfidf)
print(accuracy_score(y_test, y_pred))
print(y_pred)

0.5869565217391305
[1 1 0 0 0 2 0 1 2 0 0 2 0 1 1 0 0 1 0 1 1 2 2 1 2 1 0 0 2 0 2 1 2 2 1 2 0
 1 1 1 0 2 0 1 0 0]


C:\Users\Fernando\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:570: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


In [112]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size=0.5, random_state=0)

print(len(X_train))
print(len(X_test))

45
46


In [127]:
classifier =SGDClassifier(loss='hinge',penalty='l2',alpha=1e-3, max_iter=20, random_state=42)
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.6521739130434783


C:\Users\Fernando\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:570: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


In [128]:
classifier = MultinomialNB()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.3695652173913043


In [129]:
classifier = KMeans()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.15217391304347827


In [136]:
classifier = KNeighborsClassifier(3)
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.6521739130434783
