# Práctica 2 Ingeniería Linguística

In [36]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_files
import numpy as np
import glob
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [2]:
def open_glossary():
    file_deportes = open("./Glosarios/Glosario_deportes/glosario_deportes.txt",encoding='utf-8')
    glosario_deportes = file_deportes.read().split("\n")
    
    file_politica = open("./Glosarios/Glosario_politica/glosario_politica.txt",encoding='utf-8')
    glosario_politica = file_politica.read().split("\n")
    
    file_salud = open("./Glosarios/Glosario_salud/glosario_salud.txt",encoding='utf-8')
    glosario_salud = file_salud.read().split("\n")
    
    glosarios = [glosario_deportes,glosario_politica,glosario_salud]
    
    return glosarios

In [3]:
glosario = open_glossary()
glosario_deportes = glosario[0]
glosario_politica = glosario[1]
glosario_salud = glosario[2]

In [3]:
file = open("./Glosarios/glosario_all.txt",encoding='utf-8')
glosario = file.read().split("\n")

In [4]:
print(glosario)

['asma', 'defectos', 'medicamentos', 'salud', 'azúcar', 'caso', 'estudio', 'riesgo', 'medicación', 'embarazo', 'cirujía', 'síntomas', 'dolor', 'mujeres', 'enfermedad', 'problema', 'factores', 'pandemia', 'niños', 'productos', 'artículo', 'gobierno', 'ley', 'constitución', 'reforma', 'mayoría', 'debate', 'parte', 'rey', 'congreso', 'comisión', 'país', 'derecho', 'ministerio', 'públicos', 'comunidad', 'partido', 'laboral', 'política', 'electoral', 'ganar', 'derbi', 'Real Madrid', 'Madrid', 'Atlético de Madrid', 'Atleti', 'olímpicos', 'final', 'rival', 'partidos', 'deportivo', 'penalti', 'liga', 'fútbol', 'equipo', 'equipos', 'aficionados', 'futbolistas', 'torneo', 'club', 'balón', 'gol']


In [30]:
def load_documents(filenames):
    documents = []
    for i in filenames:
        file_document = open(i,encoding='utf-8')
        documents.append(file_document.read().split())
    
    return documents

In [33]:
filenames_deportes = glob.glob('./Documentos/Deportes/*')
filenames_politica = glob.glob('./Documentos/Politica/*')
filenames_salud = glob.glob('./Documentos/Salud/*')


documentos_deportes = load_documents(filenames_deportes)
documentos_politica = load_documents(filenames_politica)
documentos_salud = load_documents(filenames_salud)

In [53]:
##########################################

In [54]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
#nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
articles = load_files(r"./Documentos/",encoding='utf-8')
X, y = articles.data, articles.target

In [86]:
print(len(y))
print(len(X))
print(y)

91
91
[0 0 1 1 2 0 1 1 1 2 0 0 1 2 0 0 0 2 2 1 0 0 2 1 2 1 2 2 2 0 2 2 0 0 1 1 2
 1 1 0 0 0 1 1 0 2 2 0 1 0 1 0 1 0 1 0 1 2 1 2 0 1 2 0 2 0 0 1 2 2 2 0 2 2
 0 1 1 1 2 1 0 2 1 0 2 0 2 2 2 1 1]


In [56]:
documents = []
for d in range(0, len(X)):
    document = re.sub(r'\W', ' ', str(X[d]))
    document = document.lower()
    documents.append(document)

In [57]:
vectorizer_deportes = CountVectorizer(vocabulary = glosario[0],ngram_range=(1, 2))
vectorizer_politica = CountVectorizer(vocabulary = glosario[1],ngram_range=(1, 2))
vectorizer_salud = CountVectorizer(vocabulary = glosario[2],ngram_range=(1, 2))


vectorizer_ = CountVectorizer(vocabulary = glosario,ngram_range=(1, 2))

print(vectorizer_.vocabulary)

['asma', 'defectos', 'medicamentos', 'salud', 'azúcar', 'caso', 'estudio', 'riesgo', 'medicación', 'embarazo', 'cirujía', 'síntomas', 'dolor', 'mujeres', 'enfermedad', 'problema', 'factores', 'pandemia', 'niños', 'productos', 'artículo', 'gobierno', 'ley', 'constitución', 'reforma', 'mayoría', 'debate', 'parte', 'rey', 'congreso', 'comisión', 'país', 'derecho', 'ministerio', 'públicos', 'comunidad', 'partido', 'laboral', 'política', 'electoral', 'ganar', 'derbi', 'Real Madrid', 'Madrid', 'Atlético de Madrid', 'Atleti', 'olímpicos', 'final', 'rival', 'partidos', 'deportivo', 'penalti', 'liga', 'fútbol', 'equipo', 'equipos', 'aficionados', 'futbolistas', 'torneo', 'club', 'balón', 'gol']


In [58]:
X_ = vectorizer_.fit_transform(documents).toarray()
print((X_[0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 2 0 0 2 0 0 0 0 0 5 5]


In [59]:
len(X_[0])

62

In [60]:
tfidfconverter = TfidfTransformer()
X_ = tfidfconverter.fit_transform(X_).toarray()
print(X_[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.06356944 0.         0.
 0.         0.         0.10823254 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.07961789
 0.         0.08959375 0.         0.31053539 0.         0.
 0.18252539 0.         0.         0.         0.         0.
 0.67128422 0.62410604]


In [131]:
from scipy import spatial

glosario_deportes = np.zeros(X_[0].shape)
glosario_deportes[0:22] = 1
glosario_politica = np.zeros(X_[0].shape)
glosario_politica[22:42] = 1
glosario_salud = np.zeros(X_[0].shape)
glosario_salud[42:62] = 1

result = 1 - spatial.distance.cosine(X_[4], glosario_deportes)
#print(result)

X_deportes = []
X_politica = []
X_salud = []
cosine_distance_deporte = {}
cosine_distance_politica = {}
cosine_distance_salud = {}

for i in range(91):
    if y[i] == 0:
        X_deportes.append(X_[i])
        cosine_distance_deporte[i] = 1 - spatial.distance.cosine(glosario_deportes,X_[i])
        
    elif y[i] == 1:
        X_politica.append(X_[i])
        cosine_distance_politica[i] = 1 - spatial.distance.cosine(glosario_politica,X_[i])
        
    else:
        X_salud.append(X_[i])
        cosine_distance_salud[i] = 1 - spatial.distance.cosine(glosario_salud,X_[i])
    

cosine_distance_deporte  = {k: v for k, v in sorted(cosine_distance_deporte.items(), key=lambda item: item[1])}
cosine_distance_politica = {k: v for k, v in sorted(cosine_distance_politica.items(), key=lambda item: item[1])}
cosine_distance_salud = {k: v for k, v in sorted(cosine_distance_salud.items(), key=lambda item: item[1])}


print(cosine_distance_deporte)
print('####################################################################################################')
print(cosine_distance_politica)
print('####################################################################################################')
print(cosine_distance_salud)
    
  

{0: 0.0, 5: 0.0, 14: 0.0, 16: 0.0, 20: 0.0, 32: 0.0, 33: 0.0, 40: 0.0, 44: 0.0, 47: 0.0, 49: 0.0, 53: 0.0, 74: 0.0, 80: 0.0, 83: 0.0, 85: 0.0, 29: 0.0027929494264389287, 11: 0.015609058257533892, 55: 0.01615203707097912, 60: 0.02339658625127894, 39: 0.04614214357475954, 66: 0.05372589767127467, 41: 0.05929550257560212, 21: 0.06322630474895718, 65: 0.06805732002351383, 10: 0.07618645947428115, 15: 0.08117676007293373, 51: 0.08472215468683642, 63: 0.10373395442560218, 1: 0.12122534383357753, 71: 0.1532762838618743}
####################################################################################################
{8: 0.08068604103829702, 37: 0.08068604103829702, 38: 0.14383376101303358, 23: 0.19324157859200342, 19: 0.22406443261209974, 52: 0.2601851691583803, 90: 0.2697134299857581, 12: 0.28014318325432397, 56: 0.28139349138825165, 35: 0.2828750401866966, 54: 0.286757482623737, 50: 0.28728738024883027, 7: 0.31249727540217376, 34: 0.3191481494937549, 89: 0.34137163423624606, 82: 0.352751

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size=0.5, random_state=0)


print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

45
46
45
46


In [62]:
classifier = LinearSVC()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classifier.decision_function(X_test))
print(len(X_test))

0.8043478260869565
[[-0.80771244  1.08163422 -1.2820154 ]
 [-0.92720323 -0.5089225   0.44634143]
 [-0.01195369 -0.30134021 -0.62040726]
 [ 0.72537103 -0.55221725 -1.22540714]
 [-0.40474337 -0.19459103 -0.34292005]
 [-0.70881262 -1.16829827  0.91055879]
 [-0.77342779  0.04121952 -0.22622752]
 [-0.9225408   1.16751495 -1.30233533]
 [-1.09658091 -1.22413782  1.29679465]
 [-0.81667838  0.54839928 -0.71281411]
 [-1.08275107  0.82862203 -0.7507375 ]
 [-0.9363674  -1.05731519  0.99939471]
 [ 0.01996233 -0.67290889 -0.32287009]
 [-0.44203369 -0.1963677  -0.27756951]
 [-0.97996241  0.59918901 -0.63282674]
 [-0.63788245  0.23716196 -0.53724582]
 [-0.45712001 -0.91507695  0.42563172]
 [-0.78016785  0.31914127 -0.59718643]
 [-0.26481824 -0.02668755 -0.6148333 ]
 [-0.66604249  0.04765717 -0.33289674]
 [-0.37824791 -0.24653677 -0.37880616]
 [-1.14910938  0.16315419 -0.09514766]
 [-0.78511864 -0.84676668  0.65696126]
 [-0.93943453  0.59440721 -0.62871659]
 [-0.34092722 -0.62131261 -0.00920942]
 [-0.2

In [15]:
classifier = MultinomialNB()
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classifier.predict_proba(X_test))

0.8478260869565217
[[0.11241705 0.77211086 0.11547209]
 [0.141879   0.21964613 0.63847486]
 [0.46643956 0.35264953 0.18091091]
 [0.73560579 0.14479737 0.11959684]
 [0.34709942 0.33903749 0.31386309]
 [0.17296956 0.18716544 0.639865  ]
 [0.20140884 0.40970274 0.38888842]
 [0.10508869 0.78995234 0.10495897]
 [0.07454235 0.10661522 0.81884243]
 [0.21461934 0.56649839 0.21888227]
 [0.12585929 0.62026476 0.25387595]
 [0.1198379  0.18935204 0.69081005]
 [0.59165718 0.20776454 0.20057828]
 [0.28750076 0.37060379 0.34189545]
 [0.12137561 0.5535901  0.32503428]
 [0.21087903 0.51495589 0.27416509]
 [0.3419433  0.22245577 0.43560093]
 [0.2196833  0.56408689 0.21622981]
 [0.43232908 0.3661613  0.20150962]
 [0.18176482 0.54097314 0.27726204]
 [0.24847874 0.3855802  0.36594107]
 [0.10507845 0.58869315 0.3062284 ]
 [0.17941045 0.17729858 0.64329097]
 [0.15464451 0.59172959 0.2536259 ]
 [0.37406471 0.23370814 0.39222715]
 [0.40783767 0.2895397  0.30262263]
 [0.69561007 0.16088169 0.14350824]
 [0.75291

In [16]:
classifier = KNeighborsClassifier(3)
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classifier.predict_proba(X_test))

0.8478260869565217
[[0.         1.         0.        ]
 [0.         0.33333333 0.66666667]
 [0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]
 [0.33333333 0.66666667 0.        ]
 [0.         0.         1.        ]
 [0.         0.66666667 0.33333333]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         1.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         1.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.         0.66666667]
 [0.         0.66666667 0.33333333]
 [0.66666667 0.33333333 0.        ]
 [0.         0.66666667 0.33333333]
 [0.         0.66666667 0.33333333]
 [0.         0.66666667 0.33333333]
 [0.         0.         1.        ]
 [0.         0.66666667 0.33333333]
 [0.33333333 0.         0.66666667]
 [1.         0.         0.        ]
 [0.66666667 0.         0.33333333]
 [1.     

In [52]:
Tfidf_vect = TfidfVectorizer(vocabulary = glosario,ngram_range=(1, 2))
X_ = Tfidf_vect.fit(documents)

X_train, X_test, y_train, y_test = train_test_split(documents, y, test_size=0.5, random_state=0)

Train_X_Tfidf = Tfidf_vect.transform(X_train)
Test_X_Tfidf = Tfidf_vect.transform(X_test)

Modelo = MultinomialNB()
Modelo.fit(Train_X_Tfidf, y_train)
y_pred = Modelo.predict(Test_X_Tfidf)
print(accuracy_score(y_test, y_pred))

0.8478260869565217
